  # Survival Showdown made by _nitey
  # Paper 1.19.2
  # Discord: .rosed

  # Number of lobbies the server will run
  num-lobby: 1

  ############################################################
  # +------------------------------------------------------+ #
  # |                  World Configuration                 | #
  # +------------------------------------------------------+ #
  ############################################################

  # ----------------------------------
  # Hub spawn location
  hub:
    world: 'world'
    x: -200
    y: 63
    z: 568
    pitch: 0
    yaw: 0


  # ----------------------------------
  # Name of the Example worlds
  lobby-example-name: 'Lobby_Example'
  arena-example-name: 'Arena_Example'

  # ----------------------------------
  # Name format of the play worlds
  # the '#' represents the lobby's ID
  lobby-format: 'Lobby_#'
  arena-format: 'Arena_#'


