name: Survival-Showdown
version: '${project.version}'
main: com.rosed.survivalshowdown.SurvivalShowdown
api-version: '1.17'
softdepend: ['Multiverse-Core']
commands:
  lobby:
  worldinfo:
  createworld:
