  # Survival Showdown made by _nitey
  # Paper 1.19.2
  # Discord: .rosed

  # Number of lobbies the server will run
  num-lobby: 1

  ############################################################
  # +------------------------------------------------------+ #
  # |                  World Configuration                 | #
  # +------------------------------------------------------+ #
  ############################################################

  # ----------------------------------
  # Hub spawn location
  hub:
    world: 'world'
    x: -200
    y: 63
    z: 568
    pitch: 0
    yaw: 0

  # ----------------------------------
  # Name of the Example worlds
  lobby-example-name: 'Lobby_Example'
  arena-example-name: 'Arena_Example'

  # ----------------------------------
  # Name format of the play worlds
  # the '#' represents the lobby's ID
  lobby-format: 'Lobby_Copy_#'
  arena-format: 'Arena_Copy_#'

  # ----------------------------------
  # Name format of the live worlds
  # the '#' represents the lobby's ID
  live-format:
    overworld-format: 'Live_P#'
    nether-format: 'Live_P#'
    end-format: 'Live_P#'

  # ----------------------------------
  # Teleport Locations for Lobby
  lobby-location:
    x: 8
    y: 4
    z: 8
    pitch: 0
    yaw: 0

  # ----------------------------------
  # Teleport Locations for Arena
  arena-location:
    player1:
      x: 3
      y: 28
      z: -17
      pitch: 0
      yaw: 0
    player2:
      x: 3
      y: 28
      z: 29
      pitch: 0
      yaw: 179

  # ----------------------------------
  # Countdowns in seconds
  countdown:
    lobby: 20